### PR TITLE
Missing file type for buffer example

### PR DESCRIPTION
**Pull request by zaccolley**
Your example is missing a file type I think

### CODE REVIEW

**Comment by mickr** [comment]
Thanks for the fix 👍

**Comment by zeke** [comment]
```
❯ np patch
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies
 ✔ Running tests
 ✔ Bumping version
 ✔ Publishing package
 ✔ Pushing tags

 get-image-colors 1.8.1 published 🎉
```

Thanks, @zaccolley. 🍰 

Out of curiosity, what are you building with this module?

**Comment by zaccolley** [comment]
making a offline capable pwa

using your module to generate a fallback visual for when my app goes offline. Decided that I dont want to cache loads of images and a colour looks nice.

https://songkick.pink/ (try my username 'zaccolley')
https://github.com/zaccolley/songkick.pink

Before (online)
App online

After (offline)
App offline

**Comment by zeke** [comment]
Nice!

**Pull request merged**
