### PR TITLE
Add support for taking a buffer as an input.

### PR DESCRIPTION
**Pull request by mickr**
Add support for taking a buffer as an input.

### CODE REVIEW

**Comment by zeke** [comment]
Thanks @mickr, looks great! Would you mind adding a note to the readme about this feature?

**Comment by zeke** [comment]
I just [set up Travis](https://github.com/zeke/get-image-colors/pull/4) too. Can you rebase with master so CI runs on this?

**Comment by mickr** [comment]
Sure, give me a few and I'll get it fixed up.

**Comment by zeke** [comment]
I just set up `standard` too, so you'll probably need to rebase, then run `standard --fix`

**Comment by mickr** [comment]
Should be good to go.

**Comment by zeke** [comment]
Landed in 1.8.0

What are you making?

**Comment by mickr** [comment]
Thanks, I am making an image sharing application that is centered around the metadata of an image and the image itself. Showing locations, color palettes, maps, history, once connected to a social media account, show related social media information.

**Comment by zeke** [comment]
Nice!

You're probably already on the EXIF train, but if not this module is very handy: https://github.com/bwindels/exif-parser

Is your app open-source? Can I watch the progress?

**Comment by mickr** [comment]
It will be soon, it is just a weekend project right now. I'll ping you when I get it uploaded.

**Pull request merged**
